### PR TITLE
Fixed issue Regex for DecimalIntLiteral #1

### PR DESCRIPTION
**Pull request by jsinger67**
Also use double quoted representation to avoid clash with slash

### CODE REVIEW

**Comment by AumyF** [comment]
Thanks for nice pull request!

I have a question about the double-quoted representation - is it simply an alternative syntax for slash form?  [This section of the document](https://jsinger67.github.io/ParGrammar.html#terminal-representation) can be interpreted as if it is deprecated.

**Comment by jsinger67** [comment]
You're welcome.
At the beginning `parol` started with only one representation form for terminals. This was the double quoted form.
There was only one single rule saying that each terminal is a regex and if you want to use a character in it which is a regex meta character, i.e. `[`, you have to escape it.
Later a smart guy from Japan suggested additional representation forms like the one that is terminated by slashes. And another one for raw strings that should never be interpreted as regexes at all.
During the realization it turned out that the slash terminated form and the double quoted form are the same from the perspective of their behavior. In both forms you can escape regex meta characters to get their literal meaning.
So, it had no consequences to keep both forms in `parol`’s grammar, except that existing grammar descriptions can be kept in their original form.
Thus, you can use both forms interchangeably when one of them suits better. Especially when there are conflicts between the content of the regex and the delimiter you simply have another choice.

Finally, thank you for your hint about the documentation. I will have a look at it and possible do some redrafts.

**Comment by AumyF** [comment]
Thank you for your detailed explanation!

**Comment by jsinger67** [comment]
Only for [completeness](https://github.com/jsinger67/parol/issues/19)
,😊

**Pull request merged**
